# Supabase Configuration
project_id = "cycacvbiknngaoxrgzci"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://itif-syuhada.github.io/we-will-shine"]

[storage]
enabled = false
