# Funding options for We Will Shine
# This project is committed to staying free forever
# 100% of funds go to infrastructure, development, and student wellbeing

# GitHub Sponsors (When available)
# github: we-will-shine

# Open Collective (When available)
# open_collective: we-will-shine

# Custom funding links
custom: ['https://wewillshine.dev/donate', 'https://opencollective.com/we-will-shine']
